name: Deploy ProDriveNet

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload site via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/var/www/prodrivenet.com"
          rm: true
          overwrite: true
          strip_components: 0
          exclude: |
            .git
            .github/**
            README.md

      - name: Finalize on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -euxo pipefail
            sudo mkdir -p /var/www/prodrivenet.com
            sudo chown -R www-data:www-data /var/www/prodrivenet.com
            sudo find /var/www/prodrivenet.com -type d -exec chmod 755 {} \;
            sudo find /var/www/prodrivenet.com -type f -exec chmod 644 {} \;
            sudo nginx -t
            sudo systemctl reload nginx
