name: Deploy ProDriveNet

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Make sure the SSH user can write to the target folder
      - name: Prepare target dir on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -euxo pipefail
            sudo mkdir -p /var/www/prodrivenet.com
            # give current SSH user write access for upload
            sudo chown -R "$USER":"$USER" /var/www/prodrivenet.com

      - name: Upload site via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/var/www/prodrivenet.com"
          overwrite: true
          strip_components: 0
          # no `exclude` and no `rm` (not supported / caused the error)

      - name: Finalize and reload nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -euxo pipefail
            sudo chown -R www-data:www-data /var/www/prodrivenet.com
            sudo find /var/www/prodrivenet.com -type d -exec chmod 755 {} \;
            sudo find /var/www/prodrivenet.com -type f -exec chmod 644 {} \;
            sudo nginx -t
            sudo systemctl reload nginx
